# docker-compose.yml
services:
  forumcinemas-reporter:
    image: mcr.microsoft.com/playwright:v1.55.0-jammy
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    command: >
      sh -c "
        apt-get update && 
        apt-get install -y wget && 
        wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb && 
        apt-get install -y ./google-chrome-stable_current_amd64.deb && 
        rm google-chrome-stable_current_amd64.deb && 
        npm install && 
        npm start
      "